"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { formatARS } from "@/lib/format";
import type { WhatsAppOrderItem, WhatsAppOrderRow } from "@/types/database";
type OrderStatus = WhatsAppOrderRow["estado"];
interface AdminOrder extends WhatsAppOrderRow { email: string | null; role: string | null; service_local: string | null; whatsapp: string | null; customer_type: "INVITADO" | "TECNICO" | "MAYORISTA"; }
const statuses: ReadonlyArray<{ value: OrderStatus; label: string }> = [{ value: "NUEVO", label: "Nuevo" }, { value: "CONFIRMADO", label: "Confirmado" }, { value: "PREPARADO", label: "Preparado" }, { value: "ENTREGADO", label: "Entregado" }, { value: "CANCELADO", label: "Cancelado" }];
const statusClasses: Record<OrderStatus, string> = { NUEVO: "border-blue-200 bg-blue-50 text-blue-700", CONFIRMADO: "border-amber-200 bg-amber-50 text-amber-800", PREPARADO: "border-violet-200 bg-violet-50 text-violet-700", ENTREGADO: "border-green-200 bg-green-50 text-green-700", CANCELADO: "border-red-200 bg-red-50 text-red-700" };
function itemCount(items: WhatsAppOrderItem[]) { return items.reduce((total, item) => total + item.cantidad, 0); }
export function AdminOrderDashboard({ session }: { session: Session }) {
 const [orders, setOrders] = useState<AdminOrder[]>([]);
 const [filter, setFilter] = useState<"TODOS" | OrderStatus>("TODOS");
 const [loading, setLoading] = useState(true);
 const [updatingId, setUpdatingId] = useState("");
 const [error, setError] = useState("");
 const loadOrders = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/admin/orders", { headers: { Authorization: `Bearer ${session.access_token}` }, cache: "no-store" }); const payload = await response.json() as { orders?: AdminOrder[]; error?: string }; if (!response.ok) throw new Error(payload.error || "No se pudieron cargar los pedidos."); setOrders(payload.orders ?? []); } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron cargar los pedidos."); } finally { setLoading(false); } }, [session.access_token]);
 useEffect(() => { const frame = window.requestAnimationFrame(() => void loadOrders()); return () => window.cancelAnimationFrame(frame); }, [loadOrders]);
 const visibleOrders = useMemo(() => filter === "TODOS" ? orders : orders.filter((order) => order.estado === filter), [filter, orders]);
 const newCount = orders.filter((order) => order.estado === "NUEVO").length;
 const activeCount = orders.filter((order) => order.estado === "CONFIRMADO" || order.estado === "PREPARADO").length;
 const estimatedTotal = orders.filter((order) => order.estado !== "CANCELADO").reduce((total, order) => total + Number(order.total_estimated), 0);
 async function updateStatus(orderId: string, estado: OrderStatus) { setUpdatingId(orderId); setError(""); try { const response = await fetch("/api/admin/orders", { method: "POST", headers: { Authorization: `Bearer ${session.access_token}`, "Content-Type": "application/json" }, body: JSON.stringify({ orderId, estado }) }); const payload = await response.json() as { order?: WhatsAppOrderRow; error?: string }; if (!response.ok || !payload.order) throw new Error(payload.error || "No se pudo actualizar el pedido."); setOrders((current) => current.map((order) => order.id === orderId ? { ...order, ...payload.order } : order)); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo actualizar el pedido."); } finally { setUpdatingId(""); } }
 return <section className="mb-6 border-b border-borde pb-6"><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="text-sm font-black text-texto">Pedidos registrados {newCount > 0 ? `· ${newCount} nuevos` : ""}</h3><p className="mt-1 text-[11px] text-texto-suave">Mayoristas, técnicos con cuenta e invitados. No descuentan stock.</p></div><button type="button" onClick={() => void loadOrders()} disabled={loading} className="rounded-lg border border-borde-fuerte px-3 py-2 text-xs font-bold text-texto">Actualizar</button></div>
 <div className="mb-3 grid grid-cols-3 gap-2"><div className="rounded-xl border border-blue-100 bg-blue-50 p-3"><p className="text-xs">Nuevos</p><p className="text-xl font-black">{newCount}</p></div><div className="rounded-xl border border-amber-100 bg-amber-50 p-3"><p className="text-xs">En curso</p><p className="text-xl font-black">{activeCount}</p></div><div className="rounded-xl border border-green-100 bg-green-50 p-3"><p className="text-xs">Estimado</p><p className="text-sm font-black">{formatARS(estimatedTotal)}</p></div></div>
 <div className="mb-3 flex gap-1.5 overflow-x-auto pb-1"><button type="button" onClick={() => setFilter("TODOS")} className="rounded-full border px-3 py-1.5 text-xs">Todos</button>{statuses.map((s) => <button key={s.value} type="button" onClick={() => setFilter(s.value)} className={`rounded-full border px-3 py-1.5 text-xs ${filter === s.value ? statusClasses[s.value] : ""}`}>{s.label}</button>)}</div>
 {error && <p role="alert" className="mb-3 text-sm text-red-700">{error}</p>}{loading ? <p>Cargando pedidos…</p> : visibleOrders.length === 0 ? <p>No hay pedidos en este estado.</p> : <div className="max-h-[34rem] space-y-3 overflow-y-auto">{visibleOrders.map((order) => <article key={order.id} className="rounded-xl border border-borde bg-white p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black text-texto">{order.service_local || order.customer_name}</p>{order.service_local && order.service_local !== order.customer_name && <p className="text-xs">{order.customer_name}</p>}<span className="inline-block rounded-full border px-2 py-0.5 text-[10px] font-bold">{order.customer_type === "MAYORISTA" ? "Mayorista" : order.customer_type === "INVITADO" || !order.user_id ? "Invitado" : "Técnico con cuenta"}</span><p className="text-[11px] text-titanio">{new Date(order.created_at).toLocaleString("es-AR", { dateStyle: "short", timeStyle: "short" })}</p></div><p className="shrink-0 text-sm font-black">{formatARS(Number(order.total_estimated))}</p></div>
 <div className="mt-3 grid grid-cols-2 gap-2 text-xs"><p><strong>Entrega:</strong> {order.delivery}</p><p><strong>Pago:</strong> {order.payment_method || "A coordinar"}</p><p><strong>Localidad:</strong> {order.locality}</p><p><strong>Unidades:</strong> {itemCount(order.items)}</p></div><details className="mt-3 border-t border-borde pt-3"><summary className="cursor-pointer text-xs font-bold text-acero-fuerte">Ver productos y contacto</summary><div className="mt-2 space-y-2">{order.items.map((item) => <p key={`${order.id}-${item.sku}`} className="text-xs">{item.cantidad}× {item.nombre} · {formatARS(item.subtotal)}</p>)}{order.email && <p className="text-xs">{order.email}</p>}{order.whatsapp && <p className="text-xs">Teléfono: <a href={`https://wa.me/${order.whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="underline">{order.whatsapp}</a></p>}{order.notes && <p className="text-xs">Obs.: {order.notes}</p>}</div></details><div className="mt-3 flex items-center gap-2"><span className={`rounded-full border px-2 py-1 text-[10px] font-bold ${statusClasses[order.estado]}`}>{statuses.find((s) => s.value === order.estado)?.label}</span><select value={order.estado} onChange={(e) => void updateStatus(order.id, e.target.value as OrderStatus)} disabled={updatingId === order.id} className="ml-auto rounded-lg border p-2 text-xs" aria-label={`Estado del pedido de ${order.customer_name}`}>{statuses.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}</select></div></article>)}</div>}
 </section>;
}
