'use client';
import { useCallback, useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import type { SalesSummary } from '@/lib/sales/summary';
import { formatARS } from '@/lib/format';
import { useAuth } from '@/lib/auth/AuthContext';
export function AdminSalesDashboard({session}:{session:Session}) {
 const [data,setData]=useState<SalesSummary|null>(null);
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState('');
 const [needsConnection,setNeedsConnection]=useState(false);
 const [connecting,setConnecting]=useState(false);
 const {connectSalesGoogle}=useAuth();
 async function connect(){setConnecting(true);setError('');try{const message=await connectSalesGoogle();if(message){setError(message);setConnecting(false);}}catch{setError('No se pudo abrir Google. Volvé a intentar.');setConnecting(false);}}
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/admin/sales',{headers:{Authorization:`Bearer ${session.access_token}`,...(session.provider_token?{'X-Google-Access-Token':session.provider_token}:{})},cache:'no-store'});const payload=await response.json();setNeedsConnection(payload.needsGoogleConnection===true);if(!response.ok)throw new Error(payload.error);setData(payload);}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las ventas.');}finally{setLoading(false);}},[session.access_token,session.provider_token]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame);},[load]);
 const label=(month:string)=>new Date(`${month}-02T12:00:00Z`).toLocaleDateString('es-AR',{month:'long',year:'numeric',timeZone:'America/Argentina/Cordoba'});
 const variation=data&&data.previousTotals.revenue>0?(data.totals.revenue/data.previousTotals.revenue-1)*100:null;
 const max=Math.max(1,...(data?.daily.flatMap(d=>[d.current,d.previous??0])??[]));
 const points=(key:'current'|'previous')=>data?.daily.filter(d=>d[key]!==null).map(d=>`${30+(d.day-1)*300/Math.max(1,data.daily.length-1)},${155-(d[key]??0)*130/max}`).join(' ');
 return <section className="mb-6 space-y-4 text-texto"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-black">Seguimiento de ventas</h3><button type="button" onClick={()=>void load()} disabled={loading} className="rounded-lg border border-borde px-3 py-2 text-xs font-bold disabled:opacity-50">Actualizar</button></div><p className="text-xs text-texto-suave">Ventas registradas en la planilla: repuestos e insumos. Los pedidos web pendientes no se suman.</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{needsConnection&&!loading&&<div className="rounded-xl border border-borde bg-fondo-2 p-4"><p className="mb-3 text-xs">Tu planilla sigue privada. Autorizá solo lectura con tu cuenta administradora. Si Google vence el acceso, podés reconectar desde acá.</p><button type="button" onClick={()=>void connect()} disabled={connecting} className="rounded-lg bg-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{connecting?'Abriendo Google…':'Conectar Google Sheets'}</button></div>}{loading?<p role="status">Cargando ventas…</p>:!error&&data&&<>
 <p className="text-xs">{label(data.current)} hasta el día {Number(data.today.slice(8))}, comparado con {label(data.previous)} hasta el día {data.cutoff}. Incluye lo cargado hoy.</p>
 <div className="grid grid-cols-2 gap-2"><div className="rounded-xl border border-borde bg-fondo-2 p-3"><p className="text-xs">Facturación del mes</p><p className="text-lg font-black">{formatARS(data.totals.revenue)}</p><p className="mt-1 text-xs">Anterior: {formatARS(data.previousTotals.revenue)}</p></div><div className="rounded-xl border border-borde bg-fondo-2 p-3"><p className="text-xs">Variación de facturación</p><p className={`text-lg font-black ${variation===null?'':variation>=0?'text-green-700':'text-red-700'}`}>{variation===null?'Sin base anterior':`${variation>=0?'+':''}${variation.toFixed(1)}%`}</p></div><div className="col-span-2 rounded-xl border border-borde p-3"><p className="text-xs">Unidades vendidas: <strong>{data.totals.units}</strong> · Mes anterior: <strong>{data.previousTotals.units}</strong></p></div></div>
 <div className="rounded-xl border border-borde p-3"><h4 className="text-sm font-bold">Facturación acumulada por día</h4><p className="mt-1 text-xs"><span className="text-blue-700">● {label(data.current)}</span> · <span className="text-slate-600">● {label(data.previous)}</span></p><svg viewBox="0 0 360 185" role="img" aria-label="Comparación de facturación acumulada. Consultá los valores diarios debajo." className="mt-2 w-full"><text x="30" y="14" fontSize="10" fill="#475569">{formatARS(max)}</text><path d="M30 25 V155 H335" stroke="#cbd5e1" fill="none"/><polyline points={points('previous')} fill="none" stroke="#64748b" strokeWidth="3" strokeDasharray="5 4"/><polyline points={points('current')} fill="none" stroke="#1d4ed8" strokeWidth="3"/>{data.daily.length===1&&<><circle cx="30" cy={155-data.daily[0]!.current*130/max} r="4" fill="#1d4ed8"/><circle cx="30" cy={155-(data.daily[0]!.previous??0)*130/max} r="3" fill="#64748b"/></>}<text x="30" y="175" fontSize="10">Día 1</text><text x="290" y="175" fontSize="10">Día {data.daily.length}</text></svg><details><summary className="cursor-pointer text-xs font-bold">Ver valores diarios</summary><table className="mt-2 w-full text-right text-xs"><caption className="sr-only">Facturación acumulada por día</caption><thead><tr><th>Día</th><th>Este mes</th><th>Anterior</th></tr></thead><tbody>{data.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{formatARS(d.current)}</td><td>{d.previous===null?'—':formatARS(d.previous)}</td></tr>)}</tbody></table></details></div>
 <div className="rounded-xl border border-borde p-3"><h4 className="mb-3 text-sm font-bold">10 productos más vendidos del mes</h4><p className="mb-3 text-xs text-texto-suave">Por unidades. Cada producto y calidad se muestra por separado.</p>{data.top.length===0?<p className="text-xs">Todavía no hay ventas cargadas este mes.</p>:<ol className="space-y-3">{data.top.map((product,index)=><li key={product.name}><div className="flex items-start justify-between gap-2 text-xs"><span>{index+1}. {product.name}</span><strong className="shrink-0">{product.units} u.</strong></div><div className="mt-1 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-blue-600" style={{width:`${product.units/data.top[0]!.units*100}%`}}/></div><p className="mt-1 text-[11px] text-texto-suave">{formatARS(product.revenue)}</p></li>)}</ol>}</div>
 </>}</section>;
}
