import { NextResponse } from "next/server"; import { createClient } from "@supabase/supabase-js"; import { JWT } from "google-auth-library";
export const runtime="nodejs";export const dynamic="force-dynamic";
function client(t:string){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${t}`}}})}
async function admin(r:Request){const t=r.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!t)return null;const s=client(t),{data:a}=await s.auth.getUser(t);if(!a.user)return null;const{data:p}=await s.from("profiles").select("role").eq("id",a.user.id).maybeSingle();return p?.role==="ADMIN"?s:null}
async function googleToken(){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?.replace(/\\n/g,"\n");if(!email||!key)throw new Error("La conexión de escritura con Google Sheets todavía no está autorizada.");const c=new JWT({email,key,scopes:["https://www.googleapis.com/auth/spreadsheets"]});const{token}=await c.getAccessToken();if(!token)throw new Error("No se pudo autenticar Google Sheets.");return token}
async function sheetValues(token:string,range:string){const id=process.env.GOOGLE_SHEETS_SPREADSHEET_ID;if(!id)throw new Error("Falta configurar el Google Sheet.");const u=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}?valueRenderOption=UNFORMATTED_VALUE`;const r=await fetch(u,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error("No se pudo leer Google Sheets.");return (await r.json()).values as unknown[][]||[]}
async function putValues(token:string,ranges:{range:string;values:unknown[][]}[]){const id=process.env.GOOGLE_SHEETS_SPREADSHEET_ID!;const u=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values:batchUpdate`;const r=await fetch(u,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({valueInputOption:"USER_ENTERED",data:ranges})});if(!r.ok)throw new Error("No se pudo escribir Google Sheets: "+await r.text())}
export async function GET(r:Request){const s=await admin(r);if(!s)return NextResponse.json({error:"No autorizado."},{status:401});const[p,m]=await Promise.all([s.from("products").select("sku,nombre,stock_sheet,stock_efectivo,precio_costo").eq("publicado",true).order("nombre"),s.from("inventory_movements").select("id,sku,product_name,quantity,stock_before,stock_after,created_at").order("created_at",{ascending:false}).limit(30)]);if(p.error||m.error)return NextResponse.json({error:p.error?.message||m.error?.message},{status:500});return NextResponse.json({products:p.data,movements:m.data})}
export async function POST(r:Request){const s=await admin(r);if(!s)return NextResponse.json({error:"No autorizado."},{status:401});let b:any;try{b=await r.json()}catch{return NextResponse.json({error:"Solicitud inválida."},{status:400})}if(typeof b.sku!=="string"||!Number.isInteger(b.quantity)||b.quantity<=0||b.quantity>10000)return NextResponse.json({error:"Datos inválidos."},{status:400});
try{const token=await googleToken();const stock=await sheetValues(token,"Stock!A:N");const sr=stock.findIndex((row,i)=>i>=4&&String(row[13]??"").trim()===b.sku);if(sr<0)throw new Error("No encontré el SKU en la pestaña Stock.");const row=stock[sr],initial=Number(row[6]??0),sales=Number(row[7]??0),workshop=Number(row[8]??0),before=initial-sales-workshop,after=before+b.quantity;if(before<0)throw new Error("El stock del Sheet es inválido.");
const catalog=await sheetValues(token,"Catalogo!A:N");const cr=catalog.findIndex((row,i)=>i>=1&&String(row[0]??"").trim()===b.sku);if(cr<0)throw new Error("No encontré el SKU en Catalogo.");
const updates=[{range:`Stock!G${sr+1}`,values:[[initial+b.quantity]]},{range:`Catalogo!N${cr+1}`,values:[[after]]}];if(b.unitCost!=null&&Number.isFinite(b.unitCost)&&b.unitCost>=0){updates.push({range:`Stock!C${sr+1}`,values:[[b.unitCost]]},{range:`Catalogo!M${cr+1}`,values:[[b.unitCost]]})}await putValues(token,updates);
const{data,error}=await s.rpc("admin_apply_sheet_stock",{p_sku:b.sku,p_quantity:b.quantity,p_stock_before:before,p_stock_after:after,p_unit_cost:b.unitCost??null,p_note:typeof b.note==="string"?b.note.slice(0,250):null});if(error)throw error;return NextResponse.json({movement:data,sheetUpdated:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"No se pudo actualizar stock."},{status:500})}}